### ISSUE TITLE
Python 3.3 not working

### ISSUE THREAD

**Issue by AbdealiJK** [menpo/condaci#10]
Hi,

I was trying the python 3.3 build as discussed at https://github.com/menpo/cyvlfeat/issues/12 and found that the condaci script doesnt work for py3.3.

I checked the travis build https://travis-ci.org/menpo/condaci/jobs/131381820 and found that it was actually installing python3.5 in the 3.3 build too.

Also, for later user, It would be good to make an assertion statement like:
`[[ $(~/miniconda/bin/python -c "import sys; v=sys.version_info; print(str(v[0]) + '.' + str(v[1]))" ) == *"$PYTHON_VERSION"* ]]`
which would make travis fail if the version is not actually correct ?

**Comment by jabooth** [comment]
Hey @AbdealiJK,

Actually I don't there is an issue with the condaci build you linked to. `conda build` (installed in any env) takes an optional `--py` parameter to dictate which Python to build with -- condaci uses this to ensure the correct python version is built. As a concrete example, here's the log for the Python 3.4 build of menpo v0.7.0:

https://travis-ci.org/menpo/menpo/jobs/131774794#L264

The line I link to
```
> /home/travis/miniconda/bin/conda build -q ./conda --py=34
```
Is where we enforce that we get a Python 3.4 build (which we do).

Notice from earlier in the log however:

```
> /home/travis/c3d73b61-6238-4c66-93f1-00b7d2117c2f.sh -b -p /home/travis/miniconda
PREFIX=/home/travis/miniconda
installing: _cache-0.0-py35_x0 ...
installing: python-3.5.1-0 ...
installing: conda-env-2.4.5-py35_0 ...
installing: openssl-1.0.2g-0 ...
installing: pycosat-0.6.1-py35_0 ...
installing: pyyaml-3.11-py35_1 ...
installing: readline-6.2-2 ...
installing: requests-2.9.1-py35_0 ...
installing: sqlite-3.9.2-0 ...
installing: tk-8.5.18-0 ...
installing: xz-5.0.5-1 ...
installing: yaml-0.1.6-0 ...
installing: zlib-1.2.8-0 ...
installing: conda-4.0.5-py35_0 ...
installing: pycrypto-2.6.1-py35_0 ...
installing: pip-8.1.1-py35_1 ...
installing: wheel-0.29.0-py35_0 ...
installing: setuptools-20.3-py35_0 ...
Python 3.5.1 :: Continuum Analytics, Inc.
creating default environment...
installation finished.
```
That condaci actually set itself up with a Python 3.5 env to run this command in. That's no biggie, as its fine to 'cross compile' using the `--py` flag as we did.

Is your goal to add support for 3.3 for the wider community or are you working on a specific problem and this is proving to be a blocker you can't get around? If it's the latter, if I were you I'd not worry about condaci (which had a lot of logic in it that is bespoke to Menpo's build system) and just git clone this repo and run `conda build ./conda` locally in a Python 3.3 env. You can read the Travis log and see every command that condaci invokes - most of them you will not need, but you should be able to do match its behaviour easily on your local machine. If you manage to install all your dependencies for 3.3, and you run conda build, then it should work.

Hope that's of some help!

**Comment by AbdealiJK** [comment]
@jabooth Thanks for the reply :) That clears up a lot of stuff for me!

I was attempting to test python 3.3 for the [menpo/cyvlfeat](https://github.com/menpo/cyvlfeat) package and it failed. I thought this was possibly the issue, but you've explained that it is not. I'll check it out further and see what the actual issue is.

Closing as this is a mistake on my side. Thanks !
